import GraphQLProvider from '@sd-ui-admin/app/providers/ApolloProvider';
import { Sidebar } from '@sd-ui-admin/components';
import '@sd-ui-admin/styles/global.css';
import * as styles from '@sd-ui-admin/styles/globalLayout.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import QueryProvider from './providers/QueryProvider';

export const metadata: Metadata = {
  title: 'SD-UI-Admin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <GraphQLProvider>
            <div className={styles.layout}>
              <Sidebar />
              <div className={styles.contents}>
                <header className={styles.header}>
                  <div className={styles.userMenu}>👤 누군가님</div>
                </header>
                <main className={styles.main}>{children}</main>
              </div>
            </div>
          </GraphQLProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
