import GraphQLProvider from '@sd-ui-admin/app/providers/ApolloProvider';
import { Sidebar } from '@sd-ui-admin/components';
import '@sd-ui-admin/styles/global.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import QueryProvider from './providers/QueryProvider';

export const metadata: Metadata = {
  title: 'SD-UI-Admin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <GraphQLProvider>
            <div style={{ display: 'flex' }}>
              <Sidebar />
              <main style={{ marginLeft: '250px', padding: '40px', flex: 1 }}>{children}</main>
            </div>
          </GraphQLProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
